server:
  port: 9092

spring:
  application:
    name: consumer-service
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    hostname: localhost

logging:
  level:
    web: INFO


resilience4j.retry:
  instances:
    default:
      maxAttempts: 2 # How many times API retry should happen.
      waitDuration: 1s # How long should wait to make retry calls.