server:
  port: 9091

spring:
  application:
    name: math
#  cloud:
#    config:
#      enabled: false

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka

logging:
  level:
    web: INFO



