server:
  port: 9091

spring:
  application:
    name: math-service
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    hostname: localhost

logging:
  level:
    web: INFO





